# Generated by Django 4.2.5 on 2023-12-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_alter_contactus_options_profile_email_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
