# Generated by Django 4.2.5 on 2024-02-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_remove_profile_email_remove_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
