# Generated by Django 5.0.2 on 2024-04-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0010_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-picture/defult.jpg', upload_to='profile_pictures'),
        ),
    ]
