# Generated by Django 5.0.2 on 2024-04-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('published', 'Published')], default=111, max_length=10),
            preserve_default=False,
        ),
    ]
