# Generated by Django 5.0.2 on 2024-04-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productreview_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('published', 'Published')], default='In Review', max_length=10),
        ),
    ]
