# Generated by Django 4.2.5 on 2023-10-30 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_productreview_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='parent',
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('parent_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.productreview')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
