# Generated by Django 4.2.5 on 2023-10-30 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_productreview_parent_reviewreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.productreview'),
        ),
        migrations.DeleteModel(
            name='ReviewReply',
        ),
    ]
