# Generated by Django 4.2.5 on 2023-11-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_productreview_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='parent',
        ),
    ]
