# Generated by Django 4.2.5 on 2023-12-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cartorderitems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='paid_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Processing', max_length=30),
        ),
    ]
